# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

warnings_are_errors: false

r_build_args: --no-manual
r_check_args: --no-manual

os:
  - linux
  - osx
  
addons:
  apt:
    packages:
      - libgit2-dev

r:
  - release
  - oldrel

after_success:
  - Rscript -e 'covr::codecov()'